version: '3'

services:
  backend:
    container_name: viio-market-showcase-backend
    restart: always
    build:
      context: ./backend/
    ports:
      - "4040:4040"
    links:
      - mongo
    # volumes:
    #   - .:/usr/src/app
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27018:27017"

  frontend:
    container_name: viio-market-showcase-frontend
    restart: always
    build:
      context: ./frontend/
    ports:
      - "8080:8080"
